project:
  type: website
  output-dir: "build"
website:
  title: "Institut Agro Rennes-Angers"
  navbar:
    left:
      - text: ""
        icon: fa-home
        href: index.qmd
      # - text: "Données"
      #   href: list_datasets.qmd
    right:
      - text: ""
        icon: fa-github
        href: https://github.com/AgrocampusDS/demarche_statistique
  sidebar:
    contents:
      - text: "Introduction"
        href: agronome/tds.qmd
      - section: "Introduction"
        href: agronome/TD2.qmd

format:
  html:
    theme: flatly
    highlight: tango

execute: 
  echo: false
  cache: true
  message: false
  warning: false
# Important : inclure le script R
  code-overrides:
    include-before: setup.R

