---
title: "Données"
format: html
toc: true
css: style.css
---

Vous trouverez sur cette page l'ensemble des jeux de données nécessaires aux TDs de démarche statistique.

```{r setup-TD_liste, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache= FALSE, eval = TRUE, fig.show='hide', message = FALSE, warning = FALSE, results = 'markup' )
library(tidyverse)
library(kableExtra)

list_datasets  <- list.files(pattern = '.csv')  


ll <- lapply(list_datasets, function(f){
    print(f)
    # td_content <- tibble(text = readLines(f) ) %>% 
      dataset = tibble(dataset = str_remove(f, pattern = '.csv'))
      # %>% 
      # filter(str_detect(text, "title:")) %>%
      # mutate(Nom = str_remove(text, pattern = "title: [\'\"]"))    %>% 
      # mutate(Nom = str_sub(Nom, start = 1, end = -2)) %>% 
      # mutate(index = as.numeric(str_sub(TD, start =3, end = 4))) %>% 
      # mutate(index = as.numeric(str_extract(TD, "[:digit:]+"))) %>% 
      # select(-text)
})


liste_complete <- do.call('rbind', ll) %>% 
  mutate(data_url = paste0(dataset, '.csv')) 


```


# Liste des jeux de données du module

::: {.panel-tabset}
## Agronomes

```{r echo = FALSE, eval = TRUE, results='markup'}

liste_complete %>%
  mutate(Lien = cell_spec(dataset, "html", link = data_url)) %>% 
  select(-data_url)    %>%
  mutate('Jeu de données' = str_replace_all(str_to_title(dataset), c("_"= " ")), .before = 0) %>% 
  select(-dataset) %>%
  kable("html", escape = FALSE) %>%
  collapse_rows(columns = 1, valign = 'top') %>%
  kable_classic(full_width = F, html_font = "Cambria")



```

## Agroalimentaires

```{r echo = FALSE, eval = TRUE, results='markup'}

liste_complete %>%
  mutate(Lien = cell_spec(dataset, "html", link = data_url)) %>% 
  select(-data_url)    %>%
  mutate('Jeu de données' = str_replace_all(str_to_title(dataset), c("_"= " ")), .before = 0) %>% 
  select(-dataset) %>%
  kable("html", escape = FALSE) %>%
  collapse_rows(columns = 1, valign = 'top') %>%
  kable_classic(full_width = F, html_font = "Cambria")



```

:::


