---
title: "TD 14 - Comme des grands"
format: html
---

## Exercice 1 - Interpréter un modèle

L’agence de l’eau Eau-Seine-Normandie s’intéresse aux échouages d’algues vertes et d’algues rouges-brunes sur la côte normande. La surface d’échouage des algues a été mesurée sur quatre sites d’échouage, à 3 périodes de l’année et sur 14 ans et pour les 2 types d’algues (voir les données dans le jeu [echouages.csv](https://agrocampusds.github.io/demarche_statistique/donnees_echouages.csv). L’agence de l’eau souhaite comprendre les échouages d’algues, et notamment les différents facteurs qui peuvent jouer sur les échouages. Ils veulent également voir si les échouages d’algues vertes et rouges-brunes fonctionnent de la même façon. Les variables agricoles comme les épandages, les cultures, etc. ne sont pas mesurées et ne peuvent être prises en compte ici.

*Dégager une problématique dans ce contexte après notamment avoir exploré les données. Quels éléments de réponse pouvez-vous apporter à la lumière de vos analyses à l’agence de l’eau Eau-Seine-Normandie ?*
