name: website
on:
  push:
    branches:
      - dev

jobs:   
  build:
    name: Build website with rmarkdown
    runs-on: ubuntu-latest
    container: mpetienne/demarche_stat:0.33

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate slides
        run: Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"
